---
tags: [spring-boot, war, jar, gradle, maven]
projects: [spring-boot]
---
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-convert-jar-to-war
:spring_boot_docs: http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle

Spring Boot comes with two powerful plugins:

* `spring-boot-gradle-plugin`
* `spring-boot-maven-plugin`

They both essentially have feature parity and provide the ability to run Spring Boot apps from the command line as well as bundle up runnable JARs. This subject is mentioned in almost every guide at the execution phase towards the end.

A popular subject is that many people still wish to generate WAR files to be deployed inside containers. Both of these plugins support that as well. Essentially, you have to reconfigure your project to produce a WAR file and declare the embedded container dependencies as "provided". This ensures that the relevant embedded container dependencies aren't included in the WAR file.

For detailed steps on how to configure your application to create a WAR file for your container, please see:

* {spring_boot_docs}/#build-tool-plugins-maven-packaging[Packaging executable jar and war files with Maven]
* {spring_boot_docs}/#build-tool-plugins-gradle-packaging[Packaging executable jar and war files with Gradle]

NOTE: Spring Boot operates on servlet 3.0 spec containers.
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/footer.adoc[]

